SELECT COALESCE(TO_CHAR(D.DAY), 'Month:'),
       COALESCE(TO_CHAR(D.MONTH), 'Year:'),
       COALESCE(TO_CHAR(D.YEAR), 'All:'),
       COALESCE(SUM(F.QUANTITY*F.PRICE),0) AS Revenue
FROM FACTTAB F
    INNER JOIN (
        SELECT CSID
        FROM DCUSTOMER
        WHERE STATE = 'Bayern'
    ) C USING (CSID)
    RIGHT OUTER JOIN DDATE D USING(DSID)
WHERE D.YEAR = 2019
GROUP BY GROUPING SETS ((D.YEAR, D.MONTH, D.DAY), (D.YEAR, D.MONTH), (D.YEAR), ());
--GROUP BY ROLLUP ((YEAR, MONTH), DAY);