SELECT CASE WHEN GROUPING(ARTID) = 0 THEN '-----'
            ELSE 'Sum'
        END AS First,
       SALESDATE,
       ARTID,
       NAME,
       COALESCE(SUM(F.QUANTITY*F.PRICE),0) AS Revenue,
       COALESCE(SUM(SUM(F.QUANTITY*F.PRICE)) OVER(PARTITION BY SALESDATE ORDER BY ARTID), 0)
           AS RevenueAccDay
FROM FACTTAB F
    RIGHT OUTER JOIN (
        SELECT DSID, SALESDATE
        FROM DDATE
        WHERE MONTH = 201910
    ) D USING(DSID)
    PARTITION BY (SALESDATE)
    RIGHT OUTER JOIN (
        SELECT PSID, ARTID, NAME
        FROM DPRODUCT
        WHERE PRODGROUP = 'lady bicycle'
    ) P USING(PSID)
GROUP BY GROUPING SETS ( (SALESDATE, ARTID, NAME), (SALESDATE), () )
--GROUP BY ROLLUP (SALESDATE, (ARTID, NAME))
;