SELECT QUARTER,
       MONTH,
       PRODGROUP,
       SUM(F.QUANTITY*F.PRICE) AS Revenue
FROM FACTTAB F
    RIGHT OUTER JOIN (
        SELECT DSID, MONTH, QUARTER
        FROM DDATE
        WHERE YEAR = 2014
    ) D USING(DSID)
    PARTITION BY (QUARTER, MONTH)
    RIGHT OUTER JOIN (
        SELECT CSID, NAME
        FROM DCUSTOMER
        WHERE STATE = 'Bayern'
    ) C USING (CSID)
    PARTITION BY (QUARTER, MONTH, CSID)
    RIGHT OUTER JOIN DPRODUCT P USING (PSID)
--GROUP BY GROUPING SETS ( (MONTH, PRODGROUP),  (MONTH, QUARTER), (QUARTER), ())
GROUP BY ROLLUP(QUARTER, MONTH, PRODGROUP)
;