SELECT COALESCE(TO_CHAR(D.YEAR), 'Overall:') AS Year,
       COALESCE(TO_CHAR(D.MONTH), 'Year:') AS Month,
       COALESCE(TO_CHAR(P.ARTID), 'Month:') AS ArtId,
       COALESCE(TO_CHAR(P.NAME), 'Month:') AS ArtName,
       COALESCE(SUM(F.QUANTITY),0) AS Volume
FROM FACTTAB F
    INNER JOIN DDATE D USING (DSID)
    INNER JOIN DPRODUCT P USING (PSID)
WHERE PRODGROUP = 'lady bicycle'
--GROUP BY GROUPING SETS ( (YEAR, MONTH, P.ARTID, P.NAME), (YEAR, MONTH), (YEAR), () )
GROUP BY ROLLUP (YEAR, MONTH, (ARTID, NAME))
;